[build]
  functions = "functions-build"
  command = "npm run build"

[functions]
  directory = "functions-build"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
